#!/bin/bash
SHAREDDIR="/home/server/externals"
LOGDIR="$SHAREDDIR/logs"
STARTUPSCRIPTSDIR="/home/server"
COUCHDBLOG="couchdb.log"
REALTIMEAPPLOG="realtimeapp.log"

if [ -e "$SHAREDDIR/$COUCHDBLOG" ]
then
  mkdir -p "$SHAREDDIR"
  CURRENTCOUCHDBLOGDATE=$(date -r "$SHAREDDIR/$COUCHDBLOG" +%Y%m%d_%H%M%S)
  mv "$SHAREDDIR/$COUCHDBLOG" "$LOGDIR/${CURRENTCOUCHDBLOGDATE}_${COUCHDBLOG}"
fi

if [ -e "$SHAREDDIR/$REALTIMEAPPLOG" ]
then
  mkdir -p "$SHAREDDIR"
  CURRENTREALTIMEAPPLOGDATE=$(date -r "$SHAREDDIR/$REALTIMEAPPLOG" +%Y%m%d_%H%M%S)
  mv "$SHAREDDIR/$REALTIMEAPPLOG" "$LOGDIR/${CURRENTREALTIMEAPPLOGDATE}_${REALTIMEAPPLOG}"
fi

nohup /bin/bash -c $STARTUPSCRIPTSDIR/couchdb.sh &> "$SHAREDDIR/$COUCHDBLOG"&
nohup /bin/bash $STARTUPSCRIPTSDIR/realtimeapp.sh &> "$SHAREDDIR/$REALTIMEAPPLOG"&
