version: '2'

services:
  couchdb:
    image: falco/realtimeapp_db:latest
    build:
      context: ./realtimeapp_db
      dockerfile: Dockerfile
    ports:
      - "5984:5984"
      - "5986:5986"
    volumes:
      - ${COUCHDBEXTERNALSVOLUMEDIR}:/home/server/externals:rw
    mem_limit: 512M
    memswap_limit: 1G
    logging:
      driver: json-file
  node:
    image: falco/realtimeapp_node:latest
    build:
      context: ./realtimeapp_node
      dockerfile: Dockerfile
    depends_on:
      - couchdb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NODEEXTERNALSVOLUMEDIR}:/home/server/externals:rw
    mem_limit: 512M
    logging:
      driver: json-file
