version: '2'

services:
  arch:
    image: falco/arch:latest
    build:
      context: ./arch
      dockerfile: Dockerfile
  couchdb:
    image: falco/realtimeapp_db:latest
    build:
      context: ./realtimeapp_db
      dockerfile: Dockerfile
    ports:
      - "5003:5984"
      - "5004:5986"
    depends_on:
      - arch
    volumes:
      - ${COUCHDBEXTERNALSVOLUMEDIR}:/home/server/externals:rw
    mem_limit: 512M
    memswap_limit: 1G
  node:
    image: falco/realtimeapp_node:latest
    build:
      context: ./realtimeapp_node
      dockerfile: Dockerfile
    depends_on:
      - couchdb
    ports:
      - "5001:80"
      - "5002:443"
    volumes:
      - ${NODEEXTERNALSVOLUMEDIR}:/home/server/externals:rw
    mem_limit: 512M
