version: '2'

services:
  couchdb:
    image: falco/realtimeapp_db:latest
    build:
      context: ./realtimeapp_db
      dockerfile: Dockerfile
    ports:
      - "5984:5984"
      - "5986:5986"
    volumes:
      - ${COUCHDBCONFIGVOLUMEDIR}:/etc/couchdb:rw
      - ${COUCHDBEXTERNALSVOLUMEDIR}:/home/server/externals:rw
    mem_limit: 512M
    memswap_limit: 1G
    logging:
      driver: fluentd
      #driver: json-file
      options:
        #fluentd-address: "localhost:24224"
        tag: "docker.couchdb.{{.Name}}"
        #fluentd-async-connect: "true"
  node:
    image: falco/realtimeapp_node:latest
    build:
      context: ./realtimeapp_node
      dockerfile: Dockerfile
    depends_on:
      - couchdb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NODEEXTERNALSVOLUMEDIR}:/home/server/externals:rw
    mem_limit: 512M
    logging:
      driver: fluentd
      #driver: json-file
      options:
        #fluentd-address: "localhost:24224"
        tag: "docker.node.{{.Name}}"
        #fluentd-async-connect: "true"
